name: Trigger auto deployment for nudge-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nudge-backend-AutoDeployTrigger-ebad1e85-0723-4bfc-b99a-dd8d14daab3e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NUDGEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NUDGEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NUDGEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: nudgeregistry.azurecr.io
          registryUsername: ${{ secrets.NUDGEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NUDGEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: nudge-backend
          resourceGroup: DefaultResourceGroup-NEU
          imageToBuild: nudgeregistry.azurecr.io/nudge-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


